/*    */ package rikuto.manaita_plus.core;
/*    */ 
/*    */ import net.minecraftforge.fml.common.ModMetadata;
/*    */ 
/*    */ 
/*    */ public class ManaitaPlusInfoCore
/*    */ {
/*    */   public static void registerInfo(ModMetadata meta) {
/*  9 */     meta.modId = "manaita_plus";
/* 10 */     meta.name = "Manaita Plus";
/* 11 */     meta.description = "We have Manaita and we love Manaita";
/* 12 */     meta.version = "1.0.1";
/* 13 */     meta.url = "https://twitter.com/rikutto2004";
/* 14 */     meta.updateUrl = "https://dl.dropboxusercontent.com/s/7s8n1z0rtw1y6yr/Manaita%20Plus-Update.json";
/* 15 */     meta.updateJSON = "https://dl.dropboxusercontent.com/s/rewi4omw2syubvq/Manaita%20Plus-UpdateJson.json";
/* 16 */     meta.authorList.add("rikuto");
/* 17 */     meta.credits = "FMWO, defeatedcrow";
/* 18 */     meta.autogenerated = false;
/*    */   }
/*    */ }


/* Location:              H:\mc 開發用\Manaita+Plus-1.12.2-1.0.1.zip!\rikuto\manaita_plus\core\ManaitaPlusInfoCore.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */